// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxpoopedrzrdlsjrparu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cG9vcGVkcnpyZGxzanJwYXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzc4NTAsImV4cCI6MjA1Njg1Mzg1MH0.ja0fvLXCezpB-JZQhAxudHvULjrFqaHeh1vCdwY9UKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);