
import React from "react";
import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is a mesh gradient?",
    answer: "A mesh gradient is a type of gradient that uses multiple colors blended together in a more complex way than traditional linear or radial gradients. Mesh gradients create a more organic, fluid look with smooth transitions between colors, giving depth and dimension to designs."
  },
  {
    question: "Can I use these gradients for commercial projects?",
    answer: "Yes! All gradients generated with our tool are free to use for both personal and commercial projects. No attribution is required, though we always appreciate a shout-out if you love our tool."
  },
  {
    question: "How do I apply the gradient to my website?",
    answer: "Simply click the 'Copy CSS' button to copy the CSS code for your gradient. Then paste this code into your CSS file or inline style in your HTML under the background property of the element you want to style."
  },
  {
    question: "What image formats can I download the gradient in?",
    answer: "You can download your generated gradient as a PNG or JPG file. PNG is recommended for web use as it maintains quality and supports transparency if needed."
  },
  {
    question: "Can I customize the colors in the gradient?",
    answer: "Yes, our tool allows you to generate completely random gradients with the 'Generate New' button. In future updates, we plan to add more customization options for fine-tuning specific colors and positions."
  },
  {
    question: "Do mesh gradients work in all browsers?",
    answer: "The CSS generated by our tool works in all modern browsers. However, some older browsers might not support complex gradients. We recommend testing in your target browsers if backward compatibility is a concern."
  }
];

const MeshGradientFAQ = () => {
  return (
    <section className="py-16 bg-gray-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="text-3xl font-bold font-display mb-4"
          >
            Frequently Asked Questions
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            viewport={{ once: true }}
            className="text-lg text-gray-600"
          >
            Everything you need to know about our Mesh Gradient Generator
          </motion.p>
        </div>
        
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: index * 0.05 }}
              viewport={{ once: true }}
            >
              <AccordionItem value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent>
                  <p className="text-gray-600">{faq.answer}</p>
                </AccordionContent>
              </AccordionItem>
            </motion.div>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default MeshGradientFAQ;
